"""Idempotent ingestion of scraper snapshots into SQLite or PostgreSQL."""

import hashlib
import os
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Connection, Engine, URL


ROOT_DIR = Path(__file__).resolve().parents[2]
DB_PATH = os.path.join(ROOT_DIR, "shelfwatch.db")


def _connect() -> Engine:
    database_url = os.environ.get("DATABASE_URL")
    if database_url:
        if database_url.startswith("postgres://"):
            database_url = "postgresql://" + database_url.removeprefix("postgres://")
        return create_engine(database_url, pool_pre_ping=True)
    return create_engine(URL.create("sqlite", database=DB_PATH))


def init_db(conn: Connection | None = None) -> None:
    """Create the snapshots and ingest-log tables for the active database."""
    if conn is None:
        engine = _connect()
        try:
            with engine.begin() as connection:
                init_db(connection)
        finally:
            engine.dispose()
        return

    is_postgres = conn.dialect.name == "postgresql"
    identity = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if is_postgres
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    timestamp_type = "TIMESTAMP WITH TIME ZONE" if is_postgres else "TIMESTAMP"
    conn.execute(text(f"""
        CREATE TABLE IF NOT EXISTS snapshots (
            id {identity},
            source TEXT NOT NULL,
            title TEXT NOT NULL,
            price REAL,
            list_price REAL,
            discount_percent REAL,
            stock_flag TEXT NOT NULL,
            category_path TEXT,
            category_rank INTEGER,
            url TEXT,
            scraped_at {timestamp_type} NOT NULL
        )
    """))
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS ingest_log (
            run_id TEXT PRIMARY KEY,
            csv_path TEXT NOT NULL,
            rows INTEGER NOT NULL,
            ingested_at TEXT NOT NULL
        )
    """))
    conn.execute(text(
        "CREATE INDEX IF NOT EXISTS idx_source_url ON snapshots (source, url)"
    ))
    conn.execute(text(
        "CREATE INDEX IF NOT EXISTS idx_source_title ON snapshots (source, title)"
    ))
    conn.execute(text(
        "CREATE INDEX IF NOT EXISTS idx_scraped_at ON snapshots (scraped_at)"
    ))


def _file_run_id(csv_path: str) -> str:
    digest = hashlib.sha256()
    with open(csv_path, "rb") as csv_file:
        for chunk in iter(lambda: csv_file.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def ingest_latest_csv(csv_path: str, force: bool = False) -> int:
    """Append a combined CSV once per unique file content and return its rows."""
    if not os.path.exists(csv_path):
        print(f"[DB] CSV file not found: {csv_path}")
        return 0

    df = pd.read_csv(csv_path)
    if df.empty:
        print(f"[DB] CSV file is empty: {csv_path}")
        return 0

    fallback = datetime.now(timezone.utc).isoformat(timespec="seconds")
    if "scraped_at" not in df.columns:
        df["scraped_at"] = fallback
    else:
        df["scraped_at"] = df["scraped_at"].fillna(fallback)

    run_id = _file_run_id(csv_path)
    engine = _connect()
    try:
        with engine.begin() as conn:
            init_db(conn)
            existing = conn.execute(
                text("SELECT 1 FROM ingest_log WHERE run_id = :run_id"),
                {"run_id": run_id},
            ).first()
            if existing and not force:
                print(f"[DB] Already ingested (run_id {run_id[:12]}...): {csv_path}")
                return 0

            if conn.dialect.name == "postgresql":
                df["scraped_at"] = pd.to_datetime(df["scraped_at"], utc=True)
            df.to_sql(
                "snapshots",
                conn,
                if_exists="append",
                index=False,
                chunksize=500,
            )
            conn.execute(
                text("""
                    INSERT INTO ingest_log (run_id, csv_path, rows, ingested_at)
                    VALUES (:run_id, :csv_path, :rows, :ingested_at)
                    ON CONFLICT (run_id) DO UPDATE SET
                        csv_path = excluded.csv_path,
                        rows = excluded.rows,
                        ingested_at = excluded.ingested_at
                """),
                {
                    "run_id": run_id,
                    "csv_path": csv_path,
                    "rows": len(df),
                    "ingested_at": datetime.now(timezone.utc).isoformat(
                        timespec="seconds"
                    ),
                },
            )
    finally:
        engine.dispose()

    print(f"[DB] Ingested {len(df)} rows from {csv_path} (run_id {run_id[:12]}...).")
    return len(df)


def rebuild_snapshots(csv_path: str) -> int:
    """Clear local or hosted snapshots and re-ingest one clean CSV."""
    engine = _connect()
    try:
        with engine.begin() as conn:
            init_db(conn)
            conn.execute(text("DELETE FROM snapshots"))
            conn.execute(text("DELETE FROM ingest_log"))
    finally:
        engine.dispose()
    print("[DB] snapshots + ingest_log cleared for rebuild.")
    return ingest_latest_csv(csv_path, force=True)


if __name__ == "__main__":
    latest_file = os.path.normpath(os.path.join(
        ROOT_DIR, "scraper", "output", "all_products_combined.csv"
    ))
    if not os.path.exists(latest_file):
        raise FileNotFoundError(f"[DB] CSV file not found: {latest_file}")
    init_db()
    ingest_latest_csv(latest_file)
